### ISSUE TITLE
Integration of FAO 2024 data #46

### ISSUE THREAD

**Issue by theamarks** [Seafood-Globalization-Lab/artis-model#15]
There appeared to be missing species with the data test run during the close out meeting with Rahul. However, it appears this was run with the 2023 release, not the 2024 release.

Note: There have been updates to Fishbase and Sealife base (e.g., to some scientific names and common names), so we will want these integrated as part of the new run.

**Comment by theamarks** [comment]
Most of relevant code is within `01-clean-input-data.R` script of the model. Fairly sure new HS code list comes from API subscription from Comtrade

## To-do

- [x] remove hard coded filename in `classify_prod_dat()` https://github.com/Seafood-Globalization-Lab/artis-model/blob/045adecdcbfa06b7a738e29e0383e6d2c78648ab/01-clean-input-data.R#L62
- [x] ~~Add variable assignment and conditional chunk to determine which `rebuild_fao_[yyyy]()` function version to run~~ *No scenario where we would need to run release model with different fao year function.*

  
``` 
# Run the function for both versions
test_2024 <- rebuild_fao_2024_dat(datadir = datadir, filename = filename)
test_2022 <- rebuild_fao_2024_dat(datadir = datadir, filename = filename)
identical(test_2022, test_2024)
[1] TRUE
```

**Comment by theamarks** [comment]
## 2024-12-16 Update & Questions

- [ ] Why is are these species being corrected here? https://github.com/Seafood-Globalization-Lab/artis-model/blob/045adecdcbfa06b7a738e29e0383e6d2c78648ab/01-clean-input-data.R#L67C1-L76C5

**Comment by theamarks** [comment]
### 2024-12-18 Comments & Questions

- @jagephart In testing `01-clean-input-data.R` with the new `rebuild_fao_2024()` function. Does this chunk of column renaming and cleaning belong in `classify_prod_dat()` or the `rebuild_fao_2024()` function run just before that restructures the FAO data? https://github.com/Seafood-Globalization-Lab/artis-model/blob/079bc38e38da43eb8ba48a72a2f4104b26ff913f/R/classify_prod_dat.R#L26

**Comment by theamarks** [comment]
## 2025-01-02 Questions

- [ ] Is it correct that we expect "many-to-many" joins here? Would be good to make explicit in code with `relationship = "many-to-many"` arguments. Fewer warnings mean smoother runs. https://github.com/Seafood-Globalization-Lab/artis-model/blob/8b88a3f2679151d51440824b0f8d3113cf9451f1/R/classify_prod_dat.R#L424

**Comment by theamarks** [comment]
## 2025-01-15 Questions

- [ ] Thoughts on switching current `fishbase` & `sealifebase` local versioning protocol to one that uses stable "snapshot" captured by `rfishbase`?  Brought up in ARTIS discussion 👉  #44 
- [ ] I emailed the WoRMS data manager - asked if there was an avenue in the API to query historical versions of WoRMS. 

  > Database versions - in the strict sense - cannot be queried.
  We have over 200k edits/year, so it’s a very dynamic system.
  We do have monthly snapshots/dumps.

  Need to think on if ARTIS taxa matching would be ok using dynamic WoRMS database through API or `worrms::`.       Maintaining a local copy of WoRMS sounds like a big lift especially if we transition away from maintaining `fishbase` and      `sealifebase` locally. Ideally, `worrms::` package would develop a similar strategy as `rfishbase`. Both developed and maintained by `rOpenSci` group. Could float idea in a github repo issue.

**Comment by theamarks** [comment]
## 2025-01-29 Questions

- [ ] Where does this` All_HS_Codes.csv` file come from? I can't find any code in the entire model repo that looks like it creates this file, only code that reads it in. `clean_hs()` manually cleans up the `All_HS_Codes$description` text and outputs the object `hs_data_clean`. I see in the `raw_baci/` that each HS version directory has a file `product_codes_[HS_version]_[baci_version].csv` with code and description columns. My guess is that `All_HS_Codes.csv` compiles these and the script is lost somewhere? Does this file need updating with each new BACI version release?

- [ ] Do we know why `standardize_prod.R` and `standardize_baci.R` both exist? Both have nearly identical country cleaning. Do we want these country cleaning to be the same across FAO and BACI data? Differences reported below using ChatGPT to analyses scripts.

## Differences Between `standardize_prod()` and `standardize_baci()`

### **1. Variable Naming**
- `standardize_prod()`: Uses `artis_iso3c` and `artis_country_name`
- `standardize_baci()`: Uses `artis_iso3` and `artis_country_name`

### **2. Handling of Country Codes**
- **Both**: Standardize territories (U.S., U.K., France, China, Netherlands, etc.).
- **Differences**:
  - `baci()`: Adds mappings for **Taiwan** (`Other Asia, nes` → `TWN`).
  - `baci()`: Groups **Luxembourg with Belgium** (`LUX` → `BEL`).
  - `prod()`: Handles **Southern African Customs Union** (pre-2000 adjustments).
  - `prod()`: Handles **independence transitions** (Timor-Leste, Sudan, Serbia & Montenegro).

### **3. Filtering of Certain Countries**
- `prod()`: Removes historical countries (`CSK`, `SUN`, `YUG`).
- `baci()`: No such filtering.

### **4. Handling "Other nei"**
- `prod()`: Assigns `NEI` to "Other nei" in `col_country_name`.
- `baci()`: Also maps `SMR`, `AND`, and "US Misc. Pacific Isds" to `NEI`.

### **5. Country Name Standardization**
- **Both**: Use `countrycode()` to map ISO3 to country names.
- **Differences**:
  - `prod()`: Special handling for **Sudan** (`SDN`, pre-2012) and **South African Customs Union**.
  - `baci()`: Handles **Serbia and Montenegro** (`SCG`).

### **6. Order of Operations**
- `prod()`: Initializes `artis_iso3c` and `artis_country_name` as empty strings before processing.
- `baci()`: Assigns `artis_iso3` directly in `mutate()`.

## Recommendations for Streamlining
1. **Extract Shared Logic**: Most `case_when()` statements are identical. Create a helper function.
2. **Parameterize Differences**:
   - Independence transitions (needed for `prod()` only).
   - Special "Other nei" cases (`baci()` has additional mappings).
   - Country name adjustments (e.g., `SCG` vs. `ZAF`).
3. **Unify Column Naming**: Standardize on `artis_iso3` or `artis_iso3c`.

A refactored function with optional parameters could simplify maintenance while preserving flexibility.

**Comment by theamarks** [comment]
## 2025-01-31 Questions/Notes - Manual fixes vs, WoRMS matches

- [ ] Big question: If we transition to `WoRMS` classification in the future or even now as patching in missing `sciname` values, will this make it more difficult to use/join `FishBase` attribute data for analysis? Do we want to prioritize this over possible "more accurate" taxonomic table? For example, `WoRMS` and `FishBase` have different classification schemas for `osteichthyes`. This would effect genus `thunnus` that matches in `Fishbase` and how `actinopterygii` matches using `WoRMS`.  

  My plan (short of switching to a parent-child rankless classification system informed by `WoRMS`) was to expand the taxa table to include all ranks and fill in missing taxa by quering `WoRMS` API. However, this seems like it would introduce several divergent classification schemas for similar taxa. Need to think about how to handle this.
