### ISSUE TITLE
Create a CHANGELOG for releases

### ISSUE THREAD

**Issue by theamarks** [Seafood-Globalization-Lab/artis-model#41]
> **Who needs a changelog?** People do. Whether consumers or developers, the end users of software are human beings who care about what's in the software. When the software changes, people want to know why and how. 

See here for a good set of guidelines: 
[https://keepachangelog.com/en/1.1.0/](https://keepachangelog.com/en/1.1.0/)

**To-do**

- [ ] `Unreleased` section at the top to track upcoming changes. 
- [ ] `Added` for new features
- [ ] `Changed` for changes in existing functionality.
- [ ] `Deprecated` for soon-to-be removed features.
- [ ] `Removed` for now removed features
- [ ] `Fixed` for any bug fixes.
- [ ] `Security` in case of vulnerabilities.
